version: "3.7"
services:
  db:
    image: mysql
    container_name: mysql-container
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rafaelfaria
    volumes:
      - ./api/db/data:/var/lib/mysql
  api:
    build: "./api"
    container_name: node-container
    restart: "always"
    volumes:
      - ./api:/home/node/app
    ports:
      - "9001:9001"
    depends_on:
      - db
  web:
    image: php:7.2-apache
    container_name: php-container
    restart: always
    volumes:
      - ./website:/var/www/html
    ports:
      - "8888:80"
    depends_on:
      - db
      - api